# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsweep < Formula
  desc "Fast, zero-config AWS inventory TUI"
  homepage "https://github.com/advayaflow/awsweep"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Advayaflow/awsweep/releases/download/v0.1.10/awsweep_0.1.10_Darwin_x86_64.tar.gz"
      sha256 "7cc9f392786833e2026137b96054c4f5d61e51227e4379649fa4302074909109"

      define_method(:install) do
        bin.install "awsweep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Advayaflow/awsweep/releases/download/v0.1.10/awsweep_0.1.10_Darwin_arm64.tar.gz"
      sha256 "4b65dd57352fe6b84dee32c3ca04e82ac82e4ad3d40bec2e015adb215132e258"

      define_method(:install) do
        bin.install "awsweep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Advayaflow/awsweep/releases/download/v0.1.10/awsweep_0.1.10_Linux_x86_64.tar.gz"
      sha256 "918783e8b49f8065a93e14c1be55aec17448c6e6446a88a9f1fae933bae937e8"
      define_method(:install) do
        bin.install "awsweep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Advayaflow/awsweep/releases/download/v0.1.10/awsweep_0.1.10_Linux_arm64.tar.gz"
      sha256 "e04766616c6f01abf094f18ae0fac6785e48b71201d0985f63ddd15f17c5c7ce"
      define_method(:install) do
        bin.install "awsweep"
      end
    end
  end

  test do
    system "#{bin}/awsweep", "version"
  end
end
