# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerSweep < Formula
  desc "Interactive TUI to reclaim Docker disk space"
  homepage "https://github.com/advayaflow/docker-sweep"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Advayaflow/docker-sweep/releases/download/v0.1.0/docker-sweep_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "5403d4e4f784197b546c751073d3a61f6a1aafaf77fdd29c7895da6a7ab5dc6c"

      define_method(:install) do
        bin.install "docker-sweep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Advayaflow/docker-sweep/releases/download/v0.1.0/docker-sweep_0.1.0_Darwin_arm64.tar.gz"
      sha256 "73c4fa82236ff3fbd5fff92f7cbe12c921618219fef5e73e0afcf31921cbd68a"

      define_method(:install) do
        bin.install "docker-sweep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Advayaflow/docker-sweep/releases/download/v0.1.0/docker-sweep_0.1.0_Linux_x86_64.tar.gz"
      sha256 "a22e07d6976aee8e86794d9e666e2238368d9339df3ec9f4a6a8ccc01b885570"
      define_method(:install) do
        bin.install "docker-sweep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Advayaflow/docker-sweep/releases/download/v0.1.0/docker-sweep_0.1.0_Linux_arm64.tar.gz"
      sha256 "ccc2ace092b02732e663ab2a85818eb90ab75b8903813ec3d38e2f8687a76913"
      define_method(:install) do
        bin.install "docker-sweep"
      end
    end
  end

  test do
    system "#{bin}/docker-sweep", "--version"
  end
end
